---
- name: Install Apache.
  hosts: all
  become: true

  handlers:
    - name: restart apache
      service:
        name: "{{ apache_service }}"
        state: restarted

  pre_tasks:
    - name: Load variable files.
      include_vars: "{{ item }}"
      with_first_found:
        - "vars/apache_{{ ansible_os_family }}.yaml"
        - "vars/apache_default.yaml"

  tasks:
    - name: Download a file.
      get_url:
        url: http://ipv4.download.thinkbroadband.com/20MB.zip
        dest: /tmp
      environment: proxy_vars

    - name: Add an environment variable to the remote user's shell.
      lineinfile:
        dest: "~/.bash_profile"
        regexp: "^ENV_VAR= "
        line: "ENV_VAR=value"
      become: false

    - name: Get the value of an environment variable.
      shell: "source ~/.bash_profile && echo $ENV_VAR"
      register: foo

    - name: debug to view var output
      debug: msg="The var is {{ foo.stdout }}"

    - name: Ensure Apache is installed.
      package:
        name: "{{ apache_package }}"
        state: present

    - name: Make sure handlers are flushed immediately.
      meta: flush_handlers

    - name: Copy config files.
      copy:
        src: files/test.conf
        dest: "{{ apache_config_dir }}/test.conf"
      notify: restart apache

    - name: Ensure Apache is running and starts at boot.
      service:
        name: "{{ apache_service }}"
        state: started
        enabled: true
